import Foundation

enum SeedCatalog {
    static let categories: [SeedCategory] = [
        SeedCategory(name: "Fresh vegetables", defaultOrder: 0),
        SeedCategory(name: "Fresh fruits", defaultOrder: 1),
        SeedCategory(name: "Refrigerated items", defaultOrder: 2),
        SeedCategory(name: "Frozen", defaultOrder: 3),
        SeedCategory(name: "Condiments / Sauces", defaultOrder: 4),
        SeedCategory(name: "Various groceries", defaultOrder: 5),
        SeedCategory(name: "Canned foods", defaultOrder: 6),
        SeedCategory(name: "Spices & herbs", defaultOrder: 7),
        SeedCategory(name: "Dairy", defaultOrder: 8),
        SeedCategory(name: "Cheese", defaultOrder: 9),
        SeedCategory(name: "Meat", defaultOrder: 10),
        SeedCategory(name: "Seafood", defaultOrder: 11),
        SeedCategory(name: "Beverages", defaultOrder: 12),
        SeedCategory(name: "Baked goods", defaultOrder: 13),
        SeedCategory(name: "Baking", defaultOrder: 14),
        SeedCategory(name: "Snacks", defaultOrder: 15),
        SeedCategory(name: "Themed meals", defaultOrder: 16),
        SeedCategory(name: "Baby stuff", defaultOrder: 17),
        SeedCategory(name: "Pets", defaultOrder: 18),
        SeedCategory(name: "Personal care", defaultOrder: 19),
        SeedCategory(name: "Medicine", defaultOrder: 20),
        SeedCategory(name: "Kitchen", defaultOrder: 21),
        SeedCategory(name: "Cleaning products", defaultOrder: 22),
        SeedCategory(name: "Office supplies", defaultOrder: 23),
        SeedCategory(name: "Other stuff", defaultOrder: 24),
        SeedCategory(name: "Other / errands", defaultOrder: 25)
    ]

    static let entries: [SeedEntry] = [
        // Fresh vegetables
        SeedEntry(category: "Fresh vegetables", label: "Asparagus"),
        SeedEntry(category: "Fresh vegetables", label: "Broccoli"),
        SeedEntry(category: "Fresh vegetables", label: "Carrots"),
        SeedEntry(category: "Fresh vegetables", label: "Cauliflower"),
        SeedEntry(category: "Fresh vegetables", label: "Celery"),
        SeedEntry(category: "Fresh vegetables", label: "Corn"),
        SeedEntry(category: "Fresh vegetables", label: "Cucumbers"),
        SeedEntry(category: "Fresh vegetables", label: "Lettuce / Greens"),
        SeedEntry(category: "Fresh vegetables", label: "Mushrooms"),
        SeedEntry(category: "Fresh vegetables", label: "Onions"),
        SeedEntry(category: "Fresh vegetables", label: "Peppers"),
        SeedEntry(category: "Fresh vegetables", label: "Potatoes"),
        SeedEntry(category: "Fresh vegetables", label: "Spinach"),
        SeedEntry(category: "Fresh vegetables", label: "Squash"),
        SeedEntry(category: "Fresh vegetables", label: "Zucchini"),
        SeedEntry(category: "Fresh vegetables", label: "Tomatoes"),
        // Fresh fruits
        SeedEntry(category: "Fresh fruits", label: "Apples"),
        SeedEntry(category: "Fresh fruits", label: "Avocados"),
        SeedEntry(category: "Fresh fruits", label: "Bananas"),
        SeedEntry(category: "Fresh fruits", label: "Berries"),
        SeedEntry(category: "Fresh fruits", label: "Cherries"),
        SeedEntry(category: "Fresh fruits", label: "Grapefruit"),
        SeedEntry(category: "Fresh fruits", label: "Grapes"),
        SeedEntry(category: "Fresh fruits", label: "Kiwis"),
        SeedEntry(category: "Fresh fruits", label: "Lemons / Limes"),
        SeedEntry(category: "Fresh fruits", label: "Melon"),
        SeedEntry(category: "Fresh fruits", label: "Oranges"),
        SeedEntry(category: "Fresh fruits", label: "Peaches"),
        SeedEntry(category: "Fresh fruits", label: "Nectarines"),
        SeedEntry(category: "Fresh fruits", label: "Pears"),
        SeedEntry(category: "Fresh fruits", label: "Plums"),
        // Refrigerated items
        SeedEntry(category: "Refrigerated items", label: "Bagels"),
        SeedEntry(category: "Refrigerated items", label: "Chip dip"),
        SeedEntry(category: "Refrigerated items", label: "English muffins"),
        SeedEntry(category: "Refrigerated items", label: "Eggs / Fake eggs"),
        SeedEntry(category: "Refrigerated items", label: "Fruit juice"),
        SeedEntry(category: "Refrigerated items", label: "Hummus"),
        SeedEntry(category: "Refrigerated items", label: "Ready-bake breads"),
        SeedEntry(category: "Refrigerated items", label: "Tofu"),
        SeedEntry(category: "Refrigerated items", label: "Tortillas"),
        // Frozen
        SeedEntry(category: "Frozen", label: "Breakfasts"),
        SeedEntry(category: "Frozen", label: "Burritos"),
        SeedEntry(category: "Frozen", label: "Fish sticks"),
        SeedEntry(category: "Frozen", label: "Ice cream / Sorbet"),
        SeedEntry(category: "Frozen", label: "Juice concentrate"),
        SeedEntry(category: "Frozen", label: "Pizza / Pizza Rolls"),
        SeedEntry(category: "Frozen", label: "Popsicles"),
        SeedEntry(category: "Frozen", label: "Fries / Tater tots"),
        SeedEntry(category: "Frozen", label: "TV dinners"),
        SeedEntry(category: "Frozen", label: "Vegetables"),
        SeedEntry(category: "Frozen", label: "Veggie burgers"),
        // Condiments / Sauces
        SeedEntry(category: "Condiments / Sauces", label: "BBQ sauce"),
        SeedEntry(category: "Condiments / Sauces", label: "Gravy"),
        SeedEntry(category: "Condiments / Sauces", label: "Honey"),
        SeedEntry(category: "Condiments / Sauces", label: "Hot sauce"),
        SeedEntry(category: "Condiments / Sauces", label: "Jam / Jelly / Preserves"),
        SeedEntry(category: "Condiments / Sauces", label: "Ketchup / Mustard"),
        SeedEntry(category: "Condiments / Sauces", label: "Mayonnaise"),
        SeedEntry(category: "Condiments / Sauces", label: "Pasta sauce"),
        SeedEntry(category: "Condiments / Sauces", label: "Relish"),
        SeedEntry(category: "Condiments / Sauces", label: "Salad dressing"),
        SeedEntry(category: "Condiments / Sauces", label: "Salsa"),
        SeedEntry(category: "Condiments / Sauces", label: "Soy sauce"),
        SeedEntry(category: "Condiments / Sauces", label: "Steak sauce"),
        SeedEntry(category: "Condiments / Sauces", label: "Syrup"),
        SeedEntry(category: "Condiments / Sauces", label: "Worcestershire sauce"),
        // Various groceries
        SeedEntry(category: "Various groceries", label: "Bouillon cubes"),
        SeedEntry(category: "Various groceries", label: "Cereal"),
        SeedEntry(category: "Various groceries", label: "Coffee / Filters"),
        SeedEntry(category: "Various groceries", label: "Instant potatoes"),
        SeedEntry(category: "Various groceries", label: "Lemon / Lime juice"),
        SeedEntry(category: "Various groceries", label: "Mac & cheese"),
        SeedEntry(category: "Various groceries", label: "Olive oil"),
        SeedEntry(category: "Various groceries", label: "Pancake / Waffle mix"),
        SeedEntry(category: "Various groceries", label: "Pasta"),
        SeedEntry(category: "Various groceries", label: "Peanut butter"),
        SeedEntry(category: "Various groceries", label: "Pickles"),
        SeedEntry(category: "Various groceries", label: "Rice"),
        SeedEntry(category: "Various groceries", label: "Tea"),
        SeedEntry(category: "Various groceries", label: "Vegetable oil"),
        SeedEntry(category: "Various groceries", label: "Vinegar"),
        // Canned foods
        SeedEntry(category: "Canned foods", label: "Applesauce"),
        SeedEntry(category: "Canned foods", label: "Baked beans"),
        SeedEntry(category: "Canned foods", label: "Chili"),
        SeedEntry(category: "Canned foods", label: "Fruit"),
        SeedEntry(category: "Canned foods", label: "Olives"),
        SeedEntry(category: "Canned foods", label: "Tinned meats"),
        SeedEntry(category: "Canned foods", label: "Tuna / Chicken"),
        SeedEntry(category: "Canned foods", label: "Soups"),
        SeedEntry(category: "Canned foods", label: "Tomatoes"),
        SeedEntry(category: "Canned foods", label: "Veggies"),
        // Spices & herbs
        SeedEntry(category: "Spices & herbs", label: "Basil"),
        SeedEntry(category: "Spices & herbs", label: "Black pepper"),
        SeedEntry(category: "Spices & herbs", label: "Cilantro"),
        SeedEntry(category: "Spices & herbs", label: "Cinnamon"),
        SeedEntry(category: "Spices & herbs", label: "Garlic"),
        SeedEntry(category: "Spices & herbs", label: "Ginger"),
        SeedEntry(category: "Spices & herbs", label: "Mint"),
        SeedEntry(category: "Spices & herbs", label: "Oregano"),
        SeedEntry(category: "Spices & herbs", label: "Paprika"),
        SeedEntry(category: "Spices & herbs", label: "Parsley"),
        SeedEntry(category: "Spices & herbs", label: "Red pepper"),
        SeedEntry(category: "Spices & herbs", label: "Salt"),
        SeedEntry(category: "Spices & herbs", label: "Spice mix"),
        SeedEntry(category: "Spices & herbs", label: "Vanilla extract"),
        // Dairy
        SeedEntry(category: "Dairy", label: "Butter / Margarine"),
        SeedEntry(category: "Dairy", label: "Cottage cheese"),
        SeedEntry(category: "Dairy", label: "Half & half"),
        SeedEntry(category: "Dairy", label: "Milk"),
        SeedEntry(category: "Dairy", label: "Sour cream"),
        SeedEntry(category: "Dairy", label: "Whipped cream"),
        SeedEntry(category: "Dairy", label: "Yogurt"),
        // Cheese
        SeedEntry(category: "Cheese", label: "Bleu cheese"),
        SeedEntry(category: "Cheese", label: "Cheddar"),
        SeedEntry(category: "Cheese", label: "Cottage cheese"),
        SeedEntry(category: "Cheese", label: "Cream cheese"),
        SeedEntry(category: "Cheese", label: "Feta"),
        SeedEntry(category: "Cheese", label: "Goat cheese"),
        SeedEntry(category: "Cheese", label: "Mozzarella / Provolone"),
        SeedEntry(category: "Cheese", label: "Parmesan"),
        SeedEntry(category: "Cheese", label: "Provolone"),
        SeedEntry(category: "Cheese", label: "Ricotta"),
        SeedEntry(category: "Cheese", label: "Sandwich slices"),
        SeedEntry(category: "Cheese", label: "Swiss"),
        // Meat
        SeedEntry(category: "Meat", label: "Bacon / Sausage"),
        SeedEntry(category: "Meat", label: "Beef"),
        SeedEntry(category: "Meat", label: "Chicken"),
        SeedEntry(category: "Meat", label: "Ground beef / Turkey"),
        SeedEntry(category: "Meat", label: "Ham / Pork"),
        SeedEntry(category: "Meat", label: "Hot dogs"),
        SeedEntry(category: "Meat", label: "Lunchmeat"),
        SeedEntry(category: "Meat", label: "Turkey"),
        // Seafood
        SeedEntry(category: "Seafood", label: "Catfish"),
        SeedEntry(category: "Seafood", label: "Crab"),
        SeedEntry(category: "Seafood", label: "Lobster"),
        SeedEntry(category: "Seafood", label: "Mussels"),
        SeedEntry(category: "Seafood", label: "Oysters"),
        SeedEntry(category: "Seafood", label: "Salmon"),
        SeedEntry(category: "Seafood", label: "Shrimp"),
        SeedEntry(category: "Seafood", label: "Tilapia"),
        SeedEntry(category: "Seafood", label: "Tuna"),
        // Beverages
        SeedEntry(category: "Beverages", label: "Beer"),
        SeedEntry(category: "Beverages", label: "Club soda / Tonic"),
        SeedEntry(category: "Beverages", label: "Champagne"),
        SeedEntry(category: "Beverages", label: "Gin"),
        SeedEntry(category: "Beverages", label: "Juice"),
        SeedEntry(category: "Beverages", label: "Mixers"),
        SeedEntry(category: "Beverages", label: "Red wine / White wine"),
        SeedEntry(category: "Beverages", label: "Rum"),
        SeedEntry(category: "Beverages", label: "Saké"),
        SeedEntry(category: "Beverages", label: "Soda pop"),
        SeedEntry(category: "Beverages", label: "Sports drink"),
        SeedEntry(category: "Beverages", label: "Whiskey"),
        SeedEntry(category: "Beverages", label: "Vodka"),
        // Baked goods
        SeedEntry(category: "Baked goods", label: "Bagels / Croissants"),
        SeedEntry(category: "Baked goods", label: "Buns / Rolls"),
        SeedEntry(category: "Baked goods", label: "Cake / Cookies"),
        SeedEntry(category: "Baked goods", label: "Donuts / Pastries"),
        SeedEntry(category: "Baked goods", label: "Fresh bread"),
        SeedEntry(category: "Baked goods", label: "Sliced bread"),
        SeedEntry(category: "Baked goods", label: "Pie"),
        SeedEntry(category: "Baked goods", label: "Pita bread"),
        // Baking
        SeedEntry(category: "Baking", label: "Baking powder / Soda"),
        SeedEntry(category: "Baking", label: "Bread crumbs"),
        SeedEntry(category: "Baking", label: "Cake / Brownie mix"),
        SeedEntry(category: "Baking", label: "Cake icing / Decorations"),
        SeedEntry(category: "Baking", label: "Chocolate chips / Cocoa"),
        SeedEntry(category: "Baking", label: "Flour"),
        SeedEntry(category: "Baking", label: "Shortening"),
        SeedEntry(category: "Baking", label: "Sugar"),
        SeedEntry(category: "Baking", label: "Sugar substitute"),
        SeedEntry(category: "Baking", label: "Yeast"),
        // Snacks
        SeedEntry(category: "Snacks", label: "Candy / Gum"),
        SeedEntry(category: "Snacks", label: "Cookies"),
        SeedEntry(category: "Snacks", label: "Crackers"),
        SeedEntry(category: "Snacks", label: "Dried fruit"),
        SeedEntry(category: "Snacks", label: "Granola bars / Mix"),
        SeedEntry(category: "Snacks", label: "Nuts / Seeds"),
        SeedEntry(category: "Snacks", label: "Oatmeal"),
        SeedEntry(category: "Snacks", label: "Popcorn"),
        SeedEntry(category: "Snacks", label: "Potato / Corn chips"),
        SeedEntry(category: "Snacks", label: "Pretzels"),
        // Themed meals
        SeedEntry(category: "Themed meals", label: "Burger night"),
        SeedEntry(category: "Themed meals", label: "Chili night"),
        SeedEntry(category: "Themed meals", label: "Pizza night"),
        SeedEntry(category: "Themed meals", label: "Spaghetti night"),
        SeedEntry(category: "Themed meals", label: "Taco night"),
        SeedEntry(category: "Themed meals", label: "Take-out deli food"),
        // Baby stuff
        SeedEntry(category: "Baby stuff", label: "Baby food"),
        SeedEntry(category: "Baby stuff", label: "Diapers"),
        SeedEntry(category: "Baby stuff", label: "Formula"),
        SeedEntry(category: "Baby stuff", label: "Lotion"),
        SeedEntry(category: "Baby stuff", label: "Baby wash"),
        SeedEntry(category: "Baby stuff", label: "Wipes"),
        // Pets
        SeedEntry(category: "Pets", label: "Cat food / Treats"),
        SeedEntry(category: "Pets", label: "Cat litter"),
        SeedEntry(category: "Pets", label: "Dog food / Treats"),
        SeedEntry(category: "Pets", label: "Flea treatment"),
        SeedEntry(category: "Pets", label: "Pet shampoo"),
        // Personal care
        SeedEntry(category: "Personal care", label: "Antiperspirant / Deodorant"),
        SeedEntry(category: "Personal care", label: "Bath soap / Hand soap"),
        SeedEntry(category: "Personal care", label: "Condoms / Other b.c."),
        SeedEntry(category: "Personal care", label: "Cosmetics"),
        SeedEntry(category: "Personal care", label: "Cotton swabs / Balls"),
        SeedEntry(category: "Personal care", label: "Facial cleanser"),
        SeedEntry(category: "Personal care", label: "Facial tissue"),
        SeedEntry(category: "Personal care", label: "Feminine products"),
        SeedEntry(category: "Personal care", label: "Floss"),
        SeedEntry(category: "Personal care", label: "Hair gel / Spray"),
        SeedEntry(category: "Personal care", label: "Lip balm"),
        SeedEntry(category: "Personal care", label: "Moisturizing lotion"),
        SeedEntry(category: "Personal care", label: "Mouthwash"),
        SeedEntry(category: "Personal care", label: "Razors / Shaving cream"),
        SeedEntry(category: "Personal care", label: "Shampoo / Conditioner"),
        SeedEntry(category: "Personal care", label: "Sunblock"),
        SeedEntry(category: "Personal care", label: "Toilet paper"),
        SeedEntry(category: "Personal care", label: "Toothpaste"),
        SeedEntry(category: "Personal care", label: "Vitamins / Supplements"),
        // Medicine
        SeedEntry(category: "Medicine", label: "Allergy"),
        SeedEntry(category: "Medicine", label: "Antibiotic"),
        SeedEntry(category: "Medicine", label: "Antidiarrheal"),
        SeedEntry(category: "Medicine", label: "Aspirin"),
        SeedEntry(category: "Medicine", label: "Antacid"),
        SeedEntry(category: "Medicine", label: "Band-aids / Medical"),
        SeedEntry(category: "Medicine", label: "Cold / Flu / Sinus"),
        SeedEntry(category: "Medicine", label: "Pain reliever"),
        SeedEntry(category: "Medicine", label: "Prescription pick-up"),
        // Kitchen
        SeedEntry(category: "Kitchen", label: "Aluminum foil"),
        SeedEntry(category: "Kitchen", label: "Napkins"),
        SeedEntry(category: "Kitchen", label: "Non-stick spray"),
        SeedEntry(category: "Kitchen", label: "Paper towels"),
        SeedEntry(category: "Kitchen", label: "Plastic wrap"),
        SeedEntry(category: "Kitchen", label: "Sandwich / Freezer bags"),
        SeedEntry(category: "Kitchen", label: "Wax paper"),
        // Cleaning products
        SeedEntry(category: "Cleaning products", label: "Air freshener"),
        SeedEntry(category: "Cleaning products", label: "Bathroom cleaner"),
        SeedEntry(category: "Cleaning products", label: "Bleach / Detergent"),
        SeedEntry(category: "Cleaning products", label: "Dish / Dishwasher soap"),
        SeedEntry(category: "Cleaning products", label: "Garbage bags"),
        SeedEntry(category: "Cleaning products", label: "Glass cleaner"),
        SeedEntry(category: "Cleaning products", label: "Mop head / Vacuum bags"),
        SeedEntry(category: "Cleaning products", label: "Sponges / Scrubbers"),
        // Office supplies
        SeedEntry(category: "Office supplies", label: "CDRs / DVDRs"),
        SeedEntry(category: "Office supplies", label: "Notepad / Envelopes"),
        SeedEntry(category: "Office supplies", label: "Glue / Tape"),
        SeedEntry(category: "Office supplies", label: "Printer paper"),
        SeedEntry(category: "Office supplies", label: "Pens / Pencils"),
        SeedEntry(category: "Office supplies", label: "Postage stamps"),
        // Other stuff
        SeedEntry(category: "Other stuff", label: "Automotive"),
        SeedEntry(category: "Other stuff", label: "Batteries"),
        SeedEntry(category: "Other stuff", label: "Charcoal / Propane"),
        SeedEntry(category: "Other stuff", label: "Flowers / Greeting card"),
        SeedEntry(category: "Other stuff", label: "Insect repellent"),
        SeedEntry(category: "Other stuff", label: "Light bulbs"),
        SeedEntry(category: "Other stuff", label: "Newspaper / Magazine"),
        SeedEntry(category: "Other stuff", label: "Random impulse buy")
    ]
}
